name: Preview Deployment

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t atlas-app .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
      - name: Tag Docker Image
        run: |
          IMAGE_TAG=v${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker tag atlas-app jnsreeuma/atlas-app:$IMAGE_TAG
          docker tag atlas-app jnsreeuma/atlas-app:latest

      - name: Push Docker Image
        run: |
          docker push jnsreeuma/atlas-app:$IMAGE_TAG
          docker push jnsreeuma/atlas-app:latest

      - name: Start App
        run: |
          echo "Starting app..." 
          npx ts-node index.ts &
          sleep 10

      - name: Test App
        run: |
          curl --retry 5 --retry-delay 5  http://localhost:3000

      - name: Set Preview Name
        run: echo "PREVIEW_NAME=preview-pr-${{ github.event.number }}" >> $GITHUB_ENV
      
      - name: Show Preview URL
        run: echo "Preview will be at https://$PREVIEW_NAME.onrender.com"
      
      - name: Trigger Render Deploy
        run: |
          echo "Deploying to Render..."
          curl -X POST  ${{ secrets.RENDER_DEPLOY_HOOK }}
      